// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleRegistry.Infrastructure.Data;

#nullable disable

namespace VehicleRegistry.Infrastructure.Data.Migrations
{
    [DbContext(typeof(VehicleRegistryDbContext))]
    partial class VehicleRegistryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleRegistry.Core.Entities.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Manufacturers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mazda"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ferrari"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Toyota"
                        });
                });

            modelBuilder.Entity("VehicleRegistry.Core.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("YearOfManufacture")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Vehicles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Vehicles_WeightKg_Positive", "[WeightKg] > 0");

                            t.HasCheckConstraint("CK_Vehicles_YearOfManufacture", "[YearOfManufacture] >= 1886");
                        });
                });

            modelBuilder.Entity("VehicleRegistry.Core.Entities.WeightCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("MinWeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MinWeightKg")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WeightCategories", null, t =>
                        {
                            t.HasCheckConstraint("CK_WeightCategories_MinWeightKg_NonNegative", "[MinWeightKg] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconKey = "feather",
                            MinWeightKg = 0m,
                            Name = "Light"
                        },
                        new
                        {
                            Id = 2,
                            IconKey = "car",
                            MinWeightKg = 500m,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            IconKey = "truck",
                            MinWeightKg = 2500m,
                            Name = "Heavy"
                        });
                });

            modelBuilder.Entity("VehicleRegistry.Core.Entities.Vehicle", b =>
                {
                    b.HasOne("VehicleRegistry.Core.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });
#pragma warning restore 612, 618
        }
    }
}
